# Site settings
title: Andy Doyle - Mixing IT and Development
description: Mixing IT and Development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://andymdoyle.github.io/" # the base hostname & protocol for your site
twitter_username: andymdoyle
github_username:  AndyMDoyle

# Build settings
markdown: kramdown

permalink: /:title/ # /blog/:year/:month/:day/:title/

google_analytics: UA-66122866-1

disqus_shortname: AndyMDoyle

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - tailwind.config.js